// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tduldxcqtizeiiluirnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdWxkeGNxdGl6ZWlpbHVpcm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTYwOTYsImV4cCI6MjA4NzA3MjA5Nn0.995xDmnk6RMtPq4b-Dj399dTWWOG9QjvSMulfD6wCVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});